spring:

  datasource:
    url: jdbc:mariadb://maria:3306/template?createDatabaseIfNotExist=true
    username: root
    password: root

    hibernate:
      ddl-auto: validate

logging:
  file: logs/template.log
  level:
    root: info
    com.company.template: info

flyway:
  enabled: true

levelog:
  kafka:
    enabled: true

template.kafka.brokers: kafka:9092