spring:


  jpa:

    hibernate:
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  mvc:
    throw-exception-if-no-handler-found: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

  resources:
    add-mappings: false

server:
  context-path: /template
  port: 8080

security:
  basic:
    enabled: false

logging:
  level:
    root: info
    com.company.template: info

flyway:
  enabled: false

management:
  security.enabled: false